name: Docker Image CI

on:
  push:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
        
    - name: Build the Docker image
      run: docker build . -t masterkube/console:2.0
      
    - name: Docker Push
      run: docker push masterkube/console:2.0
    
    - name: 167 remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop dsn
          docker rm dsn
          docker pull masterkube/console:2.0
          docker run -d --name console -p 80:80 masterkube/console:2.0
          
    - name: 137 remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST2 }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD2 }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop dsn
          docker rm dsn
          docker pull masterkube/console:2.0
          docker run -d --name console -p 80:80 masterkube/console:2.0
